### ISSUE TITLE
Problem with <head></head>

### ISSUE THREAD

**Issue by Safi87** [thujohn/pdf-l4#116]
When I generate the pdf from View which contains <head></head> with <link> and <meta> tags the process crashes because the load of the view fails. I attach here the error:

`Exception: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/style.cls.php:482 Stack trace: #0 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/style.cls.php(482): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/app.ci...', 482, Array) #1 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/style.cls.php(2043): Style->length_in_pt('.75rem', 'auto') #2 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/style.cls.php(2082): Style->set_transform('translatex(.75r...') #3 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/style.cls.php(682): Style->set__webkit_transform('translatex(.75r...') #4 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/stylesheet.cls.php(1299): Style->__set('-webkit-transfo...', 'translateX(.75r...') #5 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/stylesheet.cls.php(1327): Stylesheet->_parse_properties('background-colo...') #6 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/stylesheet.cls.php(1077): Stylesheet->_parse_sections('.custom-switch ...') #7 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/stylesheet.cls.php(307): Stylesheet->_parse_css('/*!\n * Bootstra...') #8 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/dompdf.cls.php(570): Stylesheet->load_css_file('https://stackpa...', 3) #9 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/dompdf/include/dompdf.cls.php(696): DOMPDF->_process_html() #10 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/Pdf.php(46): DOMPDF->render() #11 /var/www/app.civitfun.com/website/vendor/thujohn/pdf/src/Thujohn/Pdf/Pdf.php(65): Thujohn\Pdf\Pdf->render() #12 /var/www/app.civitfun.com/website/app/models/Checkin.php(409): Thujohn\Pdf\Pdf->output() #13 /var/www/app.civitfun.com/website/app/controllers/AppV3/AppWsV3CheckinController.php(2435): Checkin->generatePdfs('es') #14 /var/www/app.civitfun.com/website/app/controllers/AppV3/AppWsV3CheckinController.php(4735): AppWsV3CheckinController->checkinConfirm() #15 [internal function]: AppWsV3CheckinController->confirm() #16 /var/www/app.civitfun.com/website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #17 /var/www/app.civitfun.com/website/app/controllers/AppV3/AppWsV3CheckinController.php(215): Illuminate\Routing\Controller->callAction('confirm', Array) #18 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3819): AppWsV3CheckinController->callAction('confirm', Array) #19 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3807): Illuminate\Routing\ControllerDispatcher->call(Object(AppWsV3CheckinController), Object(Illuminate\Routing\Route), 'confirm') #20 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3012): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AppWsV3CheckinC...', 'confirm') #21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #22 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3370): call_user_func_array(Object(Closure), Array) #23 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3037): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #24 /var/www/app.civitfun.com/website/bootstrap/compiled.php(3025): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #25 /var/www/app.civitfun.com/website/bootstrap/compiled.php(702): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #26 /var/www/app.civitfun.com/website/bootstrap/compiled.php(678): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #27 /var/www/app.civitfun.com/website/bootstrap/compiled.php(5797): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #28 /var/www/app.civitfun.com/website/bootstrap/compiled.php(6404): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #29 /var/www/app.civitfun.com/website/bootstrap/compiled.php(6351): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #30 /var/www/app.civitfun.com/website/bootstrap/compiled.php(8367): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #31 /var/www/app.civitfun.com/website/bootstrap/compiled.php(639): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #32 /var/www/app.civitfun.com/website/public/index.php(49): Illuminate\Foundation\Application->run() #33 {main}`

**Comment by Safi87** [comment]
This is my head tag:

`<head><meta http-equiv="content-type" content="text/html;charset=utf-8"><title>CARDEX PDF</title><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"><style>.page {page-break-before:always;}.list-style-type-none {list-style-type:none;}.list-style-type-square {list-style-type:square;}</style></head>`
